import { Footer } from "@/components/Footer";
import { Link } from "react-router-dom";
import { ArrowLeft } from "lucide-react";

export default function Terms() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <div className="max-w-3xl mx-auto px-4 py-16">
        <Link to="/" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-8">
          <ArrowLeft className="h-4 w-4" /> Back to home
        </Link>
        <h1 className="font-display text-3xl font-bold mb-8">Terms of Service</h1>
        <div className="prose prose-invert prose-sm max-w-none space-y-6 text-secondary-foreground">
          <p><strong>Last updated:</strong> April 10, 2025</p>

          <h2 className="font-display text-lg font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p>By using AuraPal, you agree to these Terms of Service. If you do not agree, please do not use our service.</p>

          <h2 className="font-display text-lg font-semibold text-foreground">2. Service Description</h2>
          <p>AuraPal provides AI-powered career tools including resume building, cover letter generation, interview preparation, and other productivity tools. Our service uses artificial intelligence to generate content based on your inputs.</p>

          <h2 className="font-display text-lg font-semibold text-foreground">3. AI-Generated Content Disclaimer</h2>
          <p>Content generated by AuraPal's AI tools is provided as suggestions and should be reviewed before use. We do not guarantee the accuracy, completeness, or suitability of AI-generated content. You are responsible for reviewing and editing all generated content before use in professional contexts.</p>

          <h2 className="font-display text-lg font-semibold text-foreground">4. Acceptable Use</h2>
          <ul className="list-disc list-inside space-y-1">
            <li>Do not use the service for illegal or fraudulent purposes</li>
            <li>Do not attempt to circumvent usage limits or rate limiting</li>
            <li>Do not share your account credentials</li>
            <li>Do not reverse-engineer, copy, or redistribute AI-generated system prompts</li>
          </ul>

          <h2 className="font-display text-lg font-semibold text-foreground">5. Subscriptions & Payments</h2>
          <p>Paid plans are billed monthly via Stripe. You may cancel at any time through your account settings. Cancellation takes effect at the end of the current billing period. We do not offer refunds for partial months.</p>

          <h2 className="font-display text-lg font-semibold text-foreground">6. Account Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time by contacting us.</p>

          <h2 className="font-display text-lg font-semibold text-foreground">7. Limitation of Liability</h2>
          <p>AuraPal is provided "as is" without warranties. We are not liable for any damages arising from the use of our service, including but not limited to career outcomes based on AI-generated content.</p>

          <h2 className="font-display text-lg font-semibold text-foreground">8. Changes to Terms</h2>
          <p>We may update these terms. Continued use after changes constitutes acceptance.</p>

          <h2 className="font-display text-lg font-semibold text-foreground">9. Contact</h2>
          <p>Questions about these terms? Contact us at <a href="mailto:contact@aurapal.org" className="text-primary hover:underline">contact@aurapal.org</a>.</p>
        </div>
      </div>
      <Footer />
    </div>
  );
}
